# -*- coding: utf-8 -*-
"""kfc_dashboard.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1exYEzCYshPcVAtFHALdcOLW0Nj1yDjdM
"""

import os
import math
from datetime import datetime, timedelta
import numpy as np
import pandas as pd
from dateutil import parser
import plotly.express as px
import plotly.graph_objects as go
from sklearn.linear_model import LinearRegression

# --------- Utilidades ----------
def ensure_dir(path="report"):
    os.makedirs(path, exist_ok=True)

def to_float_money(x):
    if pd.isna(x): return np.nan
    return float(str(x).replace("$","").replace(",","").strip())

def to_float_num(x):
    if pd.isna(x): return np.nan
    return float(str(x).replace(",","").strip())

def to_float_pct(x):
    if pd.isna(x): return np.nan
    s = str(x).replace("%","").replace(" ","").strip()
    return float(s)/100.0

def fmt_money(v):
    return f"${v:,.2f}"

def fmt_pct(v):
    return f"{100*v:.1f}%"

def week_to_dt(s):
    # Forzar día lunes si solo viene la fecha como etiqueta de semana
    try:
        dt = parser.parse(str(s), dayfirst=True)
        # Normalizar a lunes de esa semana
        return dt - timedelta(days=dt.weekday())
    except Exception:
        return pd.NaT

# --------- Carga y limpieza ----------
CSV_PATH = "Proyecto KFC - Ventas (2).csv"
df = pd.read_csv(CSV_PATH)

rename = {
    "WEEK":"week",
    "SALES":"sales_raw",
    "ORDERS":"orders_raw",
    "AOV (SALES)":"aov_raw",
    "MARKDOWN ALLY":"markdown_raw",
    "PRO ORDERS":"pro_orders_raw",
    "Select Store":"traffic_raw",
    "SS->ATC":"ss_atc_raw",
    "ATC->PTC":"atc_ptc_raw",
    "PTC->OP":"ptc_op_raw",
    "SS->ORDERS":"ss_orders_raw",
}
df = df.rename(columns=rename)

# Parsers
df["week"]           = df["week"].apply(week_to_dt)
df["sales"]          = df["sales_raw"].apply(to_float_money)
df["orders"]         = df["orders_raw"].apply(to_float_num)
df["aov"]            = df["aov_raw"].apply(to_float_money)
df["markdown"]       = df["markdown_raw"].apply(to_float_pct)
df["pro_orders"]     = df["pro_orders_raw"].apply(to_float_pct)
df["traffic"]        = df["traffic_raw"].apply(to_float_num)
df["ss_atc"]         = df["ss_atc_raw"].apply(to_float_pct)
df["atc_ptc"]        = df["atc_ptc_raw"].apply(to_float_pct)
df["ptc_op"]         = df["ptc_op_raw"].apply(to_float_pct)
df["ss_orders"]      = df["ss_orders_raw"].apply(to_float_pct)

# Orden y limpieza básica
df = df.sort_values("week").dropna(subset=["week"]).reset_index(drop=True)

# Derivadas
df["gmv_calc"] = df["orders"] * df["aov"]
df["conversion_final"] = df["ss_orders"]  # alias útil

# --------- Reporte en consola ----------
print(f"[INFO] Filas: {len(df)}, Columnas: {df.shape[1]}")
print("[INFO] Rango:", df["week"].min().date(), "→", df["week"].max().date())
print("[INFO] Nulos por columna:\n", df.isna().sum())

# --------- Visualizaciones ----------
ensure_dir("report")

# 1) Serie temporal SALES
fig_sales = px.line(df, x="week", y="sales", title="KFC - Ventas semanales")
fig_sales.write_html("report/series_sales.html", include_plotlyjs="cdn", full_html=True)

# Tendencia SALES (regresión lineal)
X = (df["week"] - df["week"].min()).dt.days.values.reshape(-1,1)
y = df["sales"].values
reg = LinearRegression().fit(X,y)
y_hat = reg.predict(X)
fig_sales_trend = go.Figure()
fig_sales_trend.add_trace(go.Scatter(x=df["week"], y=df["sales"], mode="lines", name="Sales"))
fig_sales_trend.add_trace(go.Scatter(x=df["week"], y=y_hat, mode="lines", name="Tendencia"))
fig_sales_trend.update_layout(title="KFC - Ventas con tendencia")
fig_sales_trend.write_html("report/series_sales_trend.html", include_plotlyjs="cdn", full_html=True)

# 2) Serie temporal ORDERS
fig_orders = px.line(df, x="week", y="orders", title="KFC - Órdenes semanales")
fig_orders.write_html("report/series_orders.html", include_plotlyjs="cdn", full_html=True)

# Tendencia ORDERS
y2 = df["orders"].values
reg2 = LinearRegression().fit(X,y2)
y2_hat = reg2.predict(X)
fig_orders_trend = go.Figure()
fig_orders_trend.add_trace(go.Scatter(x=df["week"], y=df["orders"], mode="lines", name="Orders"))
fig_orders_trend.add_trace(go.Scatter(x=df["week"], y=y2_hat, mode="lines", name="Tendencia"))
fig_orders_trend.update_layout(title="KFC - Órdenes con tendencia")
fig_orders_trend.write_html("report/series_orders_trend.html", include_plotlyjs="cdn", full_html=True)

# 3) Funnel semanal (porcentajes)
funnel_df = df.melt(
    id_vars=["week"],
    value_vars=["ss_atc","atc_ptc","ptc_op","ss_orders"],
    var_name="funnel_stage", value_name="rate"
)
funnel_names = {
    "ss_atc":"SS→ATC",
    "atc_ptc":"ATC→PTC",
    "ptc_op":"PTC→OP",
    "ss_orders":"SS→ORDERS"
}
funnel_df["funnel_stage"] = funnel_df["funnel_stage"].map(funnel_names)
fig_funnel = px.line(funnel_df, x="week", y="rate", color="funnel_stage", title="KFC - Funnel de conversión (%)")
fig_funnel.update_yaxes(tickformat=".1%")
fig_funnel.write_html("report/funnel.html", include_plotlyjs="cdn", full_html=True)

# 4) Tráfico vs Órdenes
fig_scatter_traffic = px.scatter(df, x="traffic", y="orders",
                                 trendline="ols",
                                 title="Tráfico (Select Store) vs Órdenes")
fig_scatter_traffic.write_html("report/scatter_traffic_orders.html", include_plotlyjs="cdn", full_html=True)

# 5) Markdown vs Ventas y vs Órdenes
fig_scatter_mark_sales = px.scatter(df, x="markdown", y="sales", trendline="ols",
                                    title="Markdown vs Ventas")
fig_scatter_mark_sales.update_xaxes(tickformat=".1%")
fig_scatter_mark_sales.write_html("report/scatter_markdown_sales.html", include_plotlyjs="cdn", full_html=True)

fig_scatter_mark_orders = px.scatter(df, x="markdown", y="orders", trendline="ols",
                                     title="Markdown vs Órdenes")
fig_scatter_mark_orders.update_xaxes(tickformat=".1%")
fig_scatter_mark_orders.write_html("report/scatter_markdown_orders.html", include_plotlyjs="cdn", full_html=True)

# --------- Escenario a 9 semanas ----------
last_date = df["week"].max()
weeks_fwd = pd.date_range(last_date + timedelta(days=7), periods=9, freq="W-MON")

# crecimiento compuesto para 9 semanas totales
traffic_last = df["traffic"].iloc[-1]
conv_last = df["conversion_final"].iloc[-1]
aov_const = df["aov"].tail(4).mean()

# asumimos +10% tráfico y +5% conversión al final (compuesto semanalmente)
traffic_growth_total = 0.10
conv_growth_total = 0.05
g_traf_week = (1 + traffic_growth_total) ** (1/9) - 1
g_conv_week = (1 + conv_growth_total) ** (1/9) - 1

proj_rows = []
t = traffic_last
c = conv_last
for w in weeks_fwd:
    t = t * (1 + g_traf_week)
    c = c * (1 + g_conv_week)
    orders_p = t * c
    sales_p = orders_p * aov_const
    proj_rows.append({"week": w, "traffic": t, "conversion_final": c,
                      "orders": orders_p, "sales": sales_p})

df_proj = pd.DataFrame(proj_rows)

# Gráfico histórico vs proyección (Órdenes)
fig_orders_proj = go.Figure()
fig_orders_proj.add_trace(go.Scatter(x=df["week"], y=df["orders"], mode="lines", name="Histórico"))
fig_orders_proj.add_trace(go.Scatter(x=df_proj["week"], y=df_proj["orders"], mode="lines", name="Proyección 9w"))
fig_orders_proj.update_layout(title="Órdenes: histórico vs proyección (9 semanas)")
fig_orders_proj.write_html("report/orders_projection.html", include_plotlyjs="cdn", full_html=True)

# Gráfico histórico vs proyección (Ventas)
fig_sales_proj = go.Figure()
fig_sales_proj.add_trace(go.Scatter(x=df["week"], y=df["sales"], mode="lines", name="Histórico"))
fig_sales_proj.add_trace(go.Scatter(x=df_proj["week"], y=df_proj["sales"], mode="lines", name="Proyección 9w"))
fig_sales_proj.update_layout(title="Ventas: histórico vs proyección (9 semanas)")
fig_sales_proj.write_html("report/sales_projection.html", include_plotlyjs="cdn", full_html=True)

# --------- Tabla resumen y HTML maestro ----------
last_8 = df.tail(8).copy()
summary = {
    "ventas_totales": df["sales"].sum(),
    "ordenes_totales": df["orders"].sum(),
    "semanas": len(df),
    "aov_promedio": df["aov"].mean(),
}

inc_ordenes = df_proj["orders"].iloc[-1] - df["orders"].iloc[-1]
inc_ventas  = df_proj["sales"].iloc[-1]  - df["sales"].iloc[-1]

# Render HTML maestro minimalista
html = f"""
<html>
<head>
  <meta charset="utf-8" />
  <title>Dashboard KFC - Semanal</title>
  <style>
    body {{ font-family: -apple-system, Segoe UI, Roboto, sans-serif; margin: 24px; }}
    h1, h2 {{ margin: 8px 0; }}
    .grid {{ display: grid; grid-template-columns: 1fr; gap: 16px; }}
    .kpi {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; }}
    .card {{ border: 1px solid #eee; border-radius: 10px; padding: 14px; }}
    table {{ border-collapse: collapse; width: 100%; }}
    th, td {{ text-align: right; padding: 6px 8px; border-bottom: 1px solid #eee; }}
    th:first-child, td:first-child {{ text-align: left; }}
    small {{ color: #666; }}
  </style>
</head>
<body>
  <h1>Dashboard KFC – Ventas, Funnel y Proyección (9 semanas)</h1>

  <div class="kpi">
    <div class="card"><b>Ventas totales</b><div>{fmt_money(summary["ventas_totales"])}</div></div>
    <div class="card"><b>Órdenes totales</b><div>{summary["ordenes_totales"]:,.0f}</div></div>
    <div class="card"><b>Semanas</b><div>{summary["semanas"]}</div></div>
    <div class="card"><b>AOV promedio</b><div>{fmt_money(summary["aov_promedio"])}</div></div>
  </div>

  <div class="grid">
    <div class="card">
      <h2>Series históricas</h2>
      <div><a href="series_sales_trend.html">Ventas con tendencia</a></div>
      <div><a href="series_orders_trend.html">Órdenes con tendencia</a></div>
      <div><a href="funnel.html">Funnel semanal (%)</a></div>
      <div><a href="scatter_traffic_orders.html">Tráfico vs Órdenes</a></div>
      <div><a href="scatter_markdown_sales.html">Markdown vs Ventas</a> | <a href="scatter_markdown_orders.html">Markdown vs Órdenes</a></div>
    </div>

    <div class="card">
      <h2>Proyección 9 semanas</h2>
      <div><a href="orders_projection.html">Órdenes: histórico vs proyección</a></div>
      <div><a href="sales_projection.html">Ventas: histórico vs proyección</a></div>
      <p><b>Incremento estimado al final de 9 semanas</b><br>
         Órdenes: {inc_ordenes:,.0f}<br>
         Ventas: {fmt_money(inc_ventas)}
      </p>
      <small>Supuestos: +10% tráfico total y +5% conversión total (compuesto), AOV constante (promedio últimas 4 semanas).</small>
    </div>

    <div class="card">
      <h2>Últimas 8 semanas (resumen)</h2>
      <table>
        <tr>
          <th>Week</th><th>Sales</th><th>Orders</th><th>Traffic</th><th>SS→ORDERS</th><th>Markdown</th><th>AOV</th>
        </tr>
        {''.join(f"<tr><td>{w.strftime('%Y-%m-%d')}</td><td>{fmt_money(s)}</td><td>{o:,.0f}</td><td>{t:,.0f}</td><td>{fmt_pct(c)}</td><td>{fmt_pct(m)}</td><td>{fmt_money(a)}</td></tr>"
                 for w,s,o,t,c,m,a in zip(last_8['week'], last_8['sales'], last_8['orders'], last_8['traffic'], last_8['conversion_final'], last_8['markdown'], last_8['aov']))}
      </table>
    </div>
  </div>
</body>
</html>
"""
with open("report/index.html","w", encoding="utf-8") as f:
    f.write(html)

print("[OK] Dashboard generado en ./report/index.html")